name: macOS

on:
  workflow_call:

# Our M1 runners are self hosted, and not ephemeral like standard GitHub action runners.
# Limit the token permissions to be read - so even if they were compromised, no damage
# could be done.
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        target: [macos-latest, [self-hosted, ARM64, macos-12.6], [self-hosted, ARM64, macos-13.2]]
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: ./scripts/build.sh test
      - run: ./scripts/install.sh

  benchmark:
    strategy:
      matrix:
        target: [macos-latest, [self-hosted, ARM64, macos-12.6], [self-hosted, ARM64, macos-13.2]]
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/benchmark.sh --transfer-count 4000

  c_sample:
    strategy:
      matrix:
        target: [macos-latest, [self-hosted, ARM64, macos-12.6], [self-hosted, ARM64, macos-13.2]]
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: ./scripts/build.sh c_sample -Drelease-safe

  docs:
    strategy:
      matrix:
        target: [macos-latest, [self-hosted, ARM64, macos-12.6], [self-hosted, ARM64, macos-13.2]]
        language: [java, go, node]
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v3

      - if: matrix.language == 'java'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # Although Maven is supposed to be installed in the
      # actions/setup-java@v3 step, it wasn't available in at least the
      # self-hosted mac runner. So we grab it manually.
      - if: matrix.language == 'java'
        run: |
          curl -o maven.zip https://dlcdn.apache.org/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.zip
          unzip maven.zip
          echo "$(pwd)/apache-maven-3.9.1/bin" >> $GITHUB_PATH

      # Runs checks against generated client docs
      - run: ./scripts/install_zig.sh
      - run: ./scripts/build.sh client_docs -- --language ${{ matrix.language }}
